// // src/redux/types/userTypes.js
// export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
// export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
// export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

// export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
// export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
// export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

// export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
// export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
// export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

// export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
// export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
// export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

